## NB developing and testing train

# LOADING WEIGHTS

In [1]:
import os
import sys
import torch
import tables as tb
import pandas as pd
import matplotlib.pyplot as plt
sys.path.append('/home/usc/ie/mpm/NEXT_graphs')

from torch_geometric.loader import DataLoader

from NEXT_graphNN.networks.architectures import GCNClass
from NEXT_graphNN.utils.train_utils import predict_gen, Metrics
from NEXT_graphNN.utils.data_loader import LabelType

### Parameters

In [111]:
data_file = '/mnt/lustre/scratch/nlsas/home/usc/ie/mpm/NEXT100/data/pressure_topology/1bar_1cm/dataset_1bar_graph_nn_all_1cm.pt'
label_type = LabelType.Classification

init_features = 4
nclass = 2

nconv = 4
mult_feat_per_conv = 2
dropout_prob = 0.1

device = 'cpu'
pred_batch = 64
saved_weights = '/mnt/lustre/scratch/nlsas/home/usc/ie/mpm/NEXT100/data/pressure_topology/1bar_1cm/gpu_train/checkpoints/net_checkpoint_58.pth.tar'

outfile = '/mnt/lustre/scratch/nlsas/home/usc/ie/mpm/NEXT100/data/pressure_topology/1bar_1cm/gpu_train/test_pred_nb.h5'

### Load net

In [112]:
model = GCNClass(init_features,
                 nclass, 
                 nconv, 
                 mult_feat_per_conv = mult_feat_per_conv, 
                 dropout_prob = dropout_prob).to(device)

### Load data

In [5]:
dataset = torch.load(data_file)
train_data, valid_data, test_data = dataset

### Produce some output before loading weights

In [21]:
loader_test = DataLoader(test_data,
                         batch_size = pred_batch,
                         shuffle = False,
                         num_workers = 1,
                         drop_last = False,
                         pin_memory = False)
    
model.eval()
softmax = torch.nn.Softmax(dim = 1)
with torch.autograd.no_grad():
    for batch in loader_test:
        batch = batch.to(device)

        out = model.forward(batch)
        break
    

In [27]:
softmax(out).cpu().detach().numpy()

array([[0.59533364, 0.40466633],
       [0.59526145, 0.4047385 ],
       [0.6207845 , 0.3792155 ],
       [0.59603935, 0.4039607 ],
       [0.59543294, 0.40456706],
       [0.59554654, 0.40445346],
       [0.6003027 , 0.39969733],
       [0.5950027 , 0.4049972 ],
       [0.633676  , 0.36632398],
       [0.59578425, 0.40421566],
       [0.59642017, 0.40357983],
       [0.59646934, 0.40353066],
       [0.63771695, 0.36228308],
       [0.59522706, 0.40477285],
       [0.5957497 , 0.40425032],
       [0.59569097, 0.40430912],
       [0.59544593, 0.4045541 ],
       [0.59714395, 0.402856  ],
       [0.59543747, 0.40456256],
       [0.59579533, 0.4042047 ],
       [0.6260353 , 0.3739647 ],
       [0.5974554 , 0.4025446 ],
       [0.62461823, 0.3753818 ],
       [0.51765466, 0.4823453 ],
       [0.6069003 , 0.3930998 ],
       [0.59518623, 0.4048138 ],
       [0.626395  , 0.37360507],
       [0.5961277 , 0.4038723 ],
       [0.62609535, 0.3739047 ],
       [0.5957452 , 0.40425488],
       [0.

In [105]:
# model.state_dict()

### Load weights

In [37]:
import copy

In [113]:
initial_dct_weights = copy.deepcopy(model.state_dict())

In [114]:
initial_dct_weights

OrderedDict([('convnorm.0.conv1.bias',
              tensor([0., 0., 0., 0., 0., 0., 0., 0.])),
             ('convnorm.0.conv1.lin.weight',
              tensor([[-0.6960, -0.2857, -0.4705,  0.3328],
                      [-0.3953,  0.2961, -0.0522, -0.3544],
                      [-0.5714,  0.5813,  0.0144, -0.4987],
                      [ 0.6627, -0.3085, -0.5909,  0.0024],
                      [-0.2920,  0.4495, -0.3203, -0.3361],
                      [-0.0359, -0.2881, -0.2071, -0.0669],
                      [ 0.1197, -0.6250,  0.6247, -0.5719],
                      [ 0.3925,  0.4046,  0.1400, -0.6088]])),
             ('convnorm.0.bnr1.module.weight',
              tensor([1., 1., 1., 1., 1., 1., 1., 1.])),
             ('convnorm.0.bnr1.module.bias',
              tensor([0., 0., 0., 0., 0., 0., 0., 0.])),
             ('convnorm.0.bnr1.module.running_mean',
              tensor([0., 0., 0., 0., 0., 0., 0., 0.])),
             ('convnorm.0.bnr1.module.running_var',
        

In [115]:
dct_weights = torch.load(saved_weights, map_location=torch.device(device))['state_dict']

load_status = model.load_state_dict(dct_weights, strict = False)

In [117]:
print('Weights loaded: ', load_status)

Weights loaded:  _IncompatibleKeys(missing_keys=[], unexpected_keys=['convnorm.4.conv1.bias', 'convnorm.4.conv1.lin.weight', 'convnorm.4.bnr1.module.weight', 'convnorm.4.bnr1.module.bias', 'convnorm.4.bnr1.module.running_mean', 'convnorm.4.bnr1.module.running_var', 'convnorm.4.bnr1.module.num_batches_tracked', 'convnorm.5.conv1.bias', 'convnorm.5.conv1.lin.weight', 'convnorm.5.bnr1.module.weight', 'convnorm.5.bnr1.module.bias', 'convnorm.5.bnr1.module.running_mean', 'convnorm.5.bnr1.module.running_var', 'convnorm.5.bnr1.module.num_batches_tracked', 'convnorm.6.conv1.bias', 'convnorm.6.conv1.lin.weight', 'convnorm.6.bnr1.module.weight', 'convnorm.6.bnr1.module.bias', 'convnorm.6.bnr1.module.running_mean', 'convnorm.6.bnr1.module.running_var', 'convnorm.6.bnr1.module.num_batches_tracked', 'convnorm.7.conv1.bias', 'convnorm.7.conv1.lin.weight', 'convnorm.7.bnr1.module.weight', 'convnorm.7.bnr1.module.bias', 'convnorm.7.bnr1.module.running_mean', 'convnorm.7.bnr1.module.running_var', 'conv

In [122]:
load_status

_IncompatibleKeys(missing_keys=[], unexpected_keys=['convnorm.4.conv1.bias', 'convnorm.4.conv1.lin.weight', 'convnorm.4.bnr1.module.weight', 'convnorm.4.bnr1.module.bias', 'convnorm.4.bnr1.module.running_mean', 'convnorm.4.bnr1.module.running_var', 'convnorm.4.bnr1.module.num_batches_tracked', 'convnorm.5.conv1.bias', 'convnorm.5.conv1.lin.weight', 'convnorm.5.bnr1.module.weight', 'convnorm.5.bnr1.module.bias', 'convnorm.5.bnr1.module.running_mean', 'convnorm.5.bnr1.module.running_var', 'convnorm.5.bnr1.module.num_batches_tracked', 'convnorm.6.conv1.bias', 'convnorm.6.conv1.lin.weight', 'convnorm.6.bnr1.module.weight', 'convnorm.6.bnr1.module.bias', 'convnorm.6.bnr1.module.running_mean', 'convnorm.6.bnr1.module.running_var', 'convnorm.6.bnr1.module.num_batches_tracked', 'convnorm.7.conv1.bias', 'convnorm.7.conv1.lin.weight', 'convnorm.7.bnr1.module.weight', 'convnorm.7.bnr1.module.bias', 'convnorm.7.bnr1.module.running_mean', 'convnorm.7.bnr1.module.running_var', 'convnorm.7.bnr1.modul

In [123]:
model.state_dict()

OrderedDict([('convnorm.0.conv1.bias',
              tensor([ 6.9866e-09, -1.1729e-09, -8.5680e-10, -7.1503e-10, -2.7893e-10,
                      -8.8031e-09, -1.6517e-09, -2.8132e-10])),
             ('convnorm.0.conv1.lin.weight',
              tensor([[ 0.0670,  0.5964, -0.3633, -0.2739],
                      [-0.3799,  0.2774,  0.0701, -0.4766],
                      [-0.3559,  0.1498, -0.6680, -0.6490],
                      [-0.1537, -0.2258,  0.2669,  0.3799],
                      [ 0.5692, -0.5313,  0.4963, -0.1242],
                      [-0.5078,  0.3688,  0.3382, -0.6365],
                      [ 0.5977,  0.4232,  0.1251, -0.5059],
                      [-0.5510, -0.1620, -0.2563,  0.6564]])),
             ('convnorm.0.bnr1.module.weight',
              tensor([0.9998, 1.0000, 1.0001, 1.0000, 1.0000, 1.0001, 1.0001, 1.0000])),
             ('convnorm.0.bnr1.module.bias',
              tensor([ 7.8156e-05, -9.0461e-05,  6.4226e-05,  5.9170e-05,  1.9051e-05,
              

In [102]:
# # Compare the state dictionaries
# for param_tensor in model.state_dict():
#     if not torch.equal(initial_dct_weights[param_tensor], model.state_dict()[param_tensor]):
#         print(f"Weights for {param_tensor} have been updated.")
        
#     else:
#         print(f"Weights for {param_tensor} remain unchanged.")

# Alternatively, check if any parameter has changed
if any(not torch.equal(initial_dct_weights[param], model.state_dict()[param]) for param in model.state_dict()):
    print("Model weights have been successfully loaded from checkpoint.")
else:
    print("Model weights have not been loaded from checkpoint.")

Model weights have been successfully loaded from checkpoint.


In [79]:
len(initial_dct_weights)

92

In [64]:
[torch.equal(initial_dct_weights[param], model.state_dict()[param]) for param in model.state_dict()]

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [44]:
# model.state_dict()

In [33]:
model.eval()
softmax = torch.nn.Softmax(dim = 1)
with torch.autograd.no_grad():
    for batch in loader_test:
        batch = batch.to(device)

        out = model.forward(batch)
        break

In [37]:
softmax(out).cpu().detach().numpy().argmax(axis = 1)

array([1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

Parece que si que carga todo bien... Voy a proceder a hacerlo entero y guardarlo entonces:

In [7]:
pred = predict_gen(test_data, 
                    model, 
                    pred_batch, 
                    device, 
                    label_type = label_type, 
                    nclass     = nclass)
coorname = ['xbin', 'ybin', 'zbin']

if label_type == LabelType.Classification:
    tname = 'EventPred'
if label_type == LabelType.Segmentation:
    tname = 'VoxelPred'
with tb.open_file(outfile, 'w') as h5out:
    for dct in pred:
        if 'coords' in dct:
            coords = dct.pop('coords')
            dct.update({c:coords[:, i] for i, c in enumerate(coorname)})
        prediction = dct.pop('prediction')
        dct.update({f'class_{i}':prediction[:, i] for i in range(prediction.shape[1])})

        df = pd.DataFrame(dct)
        df.to_hdf(outfile, tname, append=True)
#Finally we sort the output dataframe 
df = pd.read_hdf(outfile, tname).sort_values(['file_id', 'dataset_id'])
os.remove(outfile)
df.to_hdf(outfile, tname)